export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const PRODUCT_REJECT = 'PRODUCT_REJECT';
export const FETCH_ADD_CART = 'FETCH_ADD_CART';
export const ADD_CART_PENDING = 'ADD_CART_PENDING';
export const ADD_CART_REJECT = 'ADD_CART_REJECT';
